kind: Secret
apiVersion: v1
metadata:
  name: source-secret
  namespace: openshift-mtv
data:
  insecureSkipVerify: dHJ1ZQ==
  token: c2hhMjU2fkJMRndEeEFWUG9IQlJUOHc5bjJ0dUx5MUZPT3dQRlNaekMzbnYyamNCWVE=
  url: aHR0cHM6Ly9hcGkuc3RnLXlhZHU0MTkucmhvcy1wc2kuY252LXFlLnJob29kLnVzOjY0NDM=
type: Opaque

