apiVersion: forklift.konveyor.io/v1beta1
kind: NetworkMap
metadata:
  name: source-networkmap
  namespace: openshift-mtv
spec:
  map:
    - destination:
        type: pod
      source:
        type: pod
  provider:
    destination:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: Provider
      name: host
      namespace: openshift-mtv
    source:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: Provider
      name: source-provider
      namespace: openshift-mtv
