apiVersion: forklift.konveyor.io/v1beta1
kind: Plan
metadata:
  annotations:
    populatorLabels: 'True'
  name: plan-test
  namespace: openshift-mtv
spec:
  type: live
  map:
    network:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: NetworkMap
      name: source-networkmap
      namespace: openshift-mtv
    storage:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: StorageMap
      name: source-storagemap
      namespace: openshift-mtv
  migrateSharedDisks: true
  provider:
    destination:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: Provider
      name: host
      namespace: openshift-mtv
    source:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: Provider
      name: host
      namespace: openshift-mtv
  pvcNameTemplateUseGenerateName: true
  targetNamespace: default
  vms:
    - name: fedora
      namespace: mig
