apiVersion: v1
kind: Pod
metadata:
  name: verify2
spec:
  containers:
  - image: quay.io/kubevirt/cdi-importer:latest
    command:
      - sleep
      - "3600000"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeDevices:
    - devicePath: /dev/block
      name: cdi-data-vol
  volumes:
  - name: cdi-data-vol
    persistentVolumeClaim:
      claimName: fedora-40-dv-template-new
