apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: dv-source1
spec:
  source:
      http:
         url: "http://cnv-qe-server.rhevdev.lab.eng.rdu2.redhat.com/files/cnv-tests/cirros-images/cirros-0.4.0-x86_64-disk.qcow2"
  pvc:
    storageClassName: ocs-storagecluster-ceph-rbd
    volumeMode: Block
    accessModes:
     - ReadWriteMany
    resources:
      requests:
        storage: 2Gi
