apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: dv-clone-from-das
spec:
  sourceRef:
    kind: DataSource
    name: test-das
    namespace: ns1
  storage:
    accessModes:
      - ReadWriteOnce
    volumeMode: Block
    resources:
      requests:
        storage: 1Gi
