apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: dv-clone
spec:
  source:
    snapshot:
      namespace: ns1
      name: golden-volumesnapshot
  storage:
    accessModes:
      - ReadWriteOnce
    volumeMode: Filesystem
    resources:
      requests:
        storage: 2Gi
