apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: snap-source
spec:
  source:
      http:
         url: http://cnv-qe-server.rhevdev.lab.eng.rdu2.redhat.com/files/cnv-tests/cirros-images/cirros-0.4.0-x86_64-disk.qcow2
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    volumeMode: Block
