apiVersion: migrations.kubevirt.io/v1alpha1
kind: MultiNamespaceVirtualMachineStorageMigrationPlan
metadata:
  name: multi-mig-plan1
spec:
  namespaces:
  - name: mig
    virtualMachines:
    - name: fedora
      targetMigrationPVCs:
      - volumeName: rootdisk
        destinationPVC:
          name: fedora-pvc
          storageClassName: ocs-storagecluster-ceph-rbd
          accessModes:
            - ReadWriteMany
          volumeMode: Block
