apiVersion: migrations.kubevirt.io/v1alpha1
kind: MultiNamespaceVirtualMachineStorageMigration
metadata:
  name: multi-mig-migration-hotplug
spec:
  multiNamespaceVirtualMachineStorageMigrationPlanRef: 
    name: "multi-mig-plan-hotplug"
